# Generated by Django 3.0.8 on 2020-08-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasoseolapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jasoseol',
            old_name='content',
            new_name='body',
        ),
        migrations.AlterField(
            model_name='jasoseol',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
